# Permalinks
permalink:           pretty

# Setup
title:               ringoshin
tagline:             Random Data Science Thoughts
url:                 http://ringoshin.github.io
paginate:            2
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Fan Yeng-Loon
  url:               https://www.linkedin.com/in/fan-yeng-loon/
  email:             ringoshin@gmail.com

# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/ringoshin

# Gems
gems:
  - jekyll-paginate
  - jekyll-gist

# Page List
pages_list:       
  About: '/about'
  Archive: '/archive'
  Feed: '/index.html'
